### ISSUE TITLE
Configurable Node version?

### ISSUE THREAD

**Issue by Binarytales** [heroku/docker-nodejs#1]
Would it be possible to make the version of Node (and NPM) installed configurable in a similar manner to the Node Buildpack?

**Comment by Binarytales** [comment]
I now realise I made a fundamental mistake in my understand of how Docker works. I though the commands in the Dockerfile were run each time a new image was built. Instead my Dockerfile makes additive changes to the already "compiled" heroku:node image meaning that build time change of images is not possible.

It looks like there are plans to create multiple tagged image files for supported version of Node.

**Comment by friism** [comment]
@Binarytales that's right!

For now, you can grab the [node Dockerfile](https://github.com/heroku/docker-nodejs), remove the `ONBUILD` from the lines that start with that and start playing around.

Let us know if you have other questions or have feedback.

Michael
